name: test build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip]') }}
    strategy:
      matrix:
        include:
          - platform: "windows-latest"
            args: ""
    runs-on: ${{ matrix.platform }}
    env:
      working-directory: ./crates/frontend
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@lts
      - name: install frontend deps
        run: pnpm install
      - uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ${{ env.working-directory }}
          tauriScript: "pnpm tauri"
          args: ${{ matrix.args }}

      - name: release (windows)
        if: ${{ matrix.platform == 'windows-latest' }}
        uses: actions/upload-artifact@v7
        with:
          name: app
          path: | 
            ${{ github.workspace }}/target/release/bundle/nsis/*.exe
            ${{ github.workspace }}/target/release/bundle/msi/*.msi
#      - name: release (windows)
#        if: ${{ matrix.platform == 'ubuntu-latest' }}
#        uses: actions/upload-artifact@v7
#        with:
#          name: app
#          path: |
#            ${{ github.workspace }}/target/release/bundle/nsis/*.exe
#            ${{ github.workspace }}/target/release/bundle/msi/*.msi
#      - name: release (windows)
#        if: ${{ matrix.platform == 'macos-latest' }}
#        uses: actions/upload-artifact@v7
#        with:
#          name: app
#          path: |
#            ${{ github.workspace }}/target/release/bundle/nsis/*.exe
#            ${{ github.workspace }}/target/release/bundle/msi/*.msi